# Generated by Django 4.2.25 on 2025-11-05 12:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRPEP',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('TH_urid', models.CharField(default=uuid.uuid4, editable=False, max_length=36)),
                ('category', models.CharField(blank=True, choices=[('GENERAL', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], max_length=20, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('marks_obtained', models.IntegerField(blank=True, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('block', models.ForeignKey(db_column='block_id', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='core.masterblock')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crpep', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_crpep', to='core.masteruser')),
                ('district', models.ForeignKey(db_column='district_id', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='core.masterdistrict')),
                ('gram_panchayat', models.ForeignKey(db_column='panchayat_id', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='core.masterpanchayat')),
                ('master_user', models.ForeignKey(blank=True, db_column='user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crpep_account', to='core.masteruser')),
                ('nodal_clf', models.ForeignKey(blank=True, db_column='clf_code', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clf_nodal', to='core.masterclflist', to_field='clf_code')),
                ('shg', models.ForeignKey(blank=True, db_column='shg_code', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.mastershglist', to_field='shg_code')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_crpep', to='core.masteruser')),
            ],
            options={
                'db_table': 'epSakhi_crpep',
            },
        ),
        migrations.CreateModel(
            name='BeneficiaryEnterprise',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('TH_urid', models.CharField(default=uuid.uuid4, editable=False, max_length=36)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('enterprise_name', models.CharField(max_length=255)),
                ('enterprise_type', models.CharField(blank=True, max_length=255, null=True)),
                ('ownership_type', models.CharField(blank=True, max_length=255, null=True)),
                ('year_of_establishment', models.IntegerField(blank=True, null=True)),
                ('raw_material', models.TextField(blank=True, null=True)),
                ('machinery_equipment', models.TextField(blank=True, null=True)),
                ('workplace_type', models.CharField(blank=True, max_length=255, null=True)),
                ('electricity_available', models.BooleanField(default=False)),
                ('water_available', models.BooleanField(default=False)),
                ('transportation_facility', models.CharField(blank=True, max_length=255, null=True)),
                ('initial_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('source_of_investment', models.CharField(blank=True, max_length=255, null=True)),
                ('working_capital_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('annual_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('profit_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('loan_details', models.TextField(blank=True, null=True)),
                ('main_product_service', models.TextField(blank=True, null=True)),
                ('product_features', models.TextField(blank=True, null=True)),
                ('production_capacity', models.CharField(blank=True, max_length=255, null=True)),
                ('packaging_branding_status', models.CharField(blank=True, max_length=255, null=True)),
                ('certification_registration', models.CharField(blank=True, max_length=255, null=True)),
                ('target_customers', models.TextField(blank=True, null=True)),
                ('marketing_channels', models.TextField(blank=True, null=True)),
                ('monthly_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('marketing_strategy', models.TextField(blank=True, null=True)),
                ('marketing_challenges', models.TextField(blank=True, null=True)),
                ('training_received', models.TextField(blank=True, null=True)),
                ('skills_acquired', models.TextField(blank=True, null=True)),
                ('future_training_requirements', models.TextField(blank=True, null=True)),
                ('institutional_support', models.TextField(blank=True, null=True)),
                ('financial_coordination', models.TextField(blank=True, null=True)),
                ('market_linkage', models.TextField(blank=True, null=True)),
                ('mentorship_support', models.TextField(blank=True, null=True)),
                ('expansion_plan', models.TextField(blank=True, null=True)),
                ('required_support', models.TextField(blank=True, null=True)),
                ('photo_enterprise', models.ImageField(blank=True, null=True, upload_to='epSakhi/enterprise_photos/%Y/%m/')),
                ('photo_entrepreneur', models.ImageField(blank=True, null=True, upload_to='epSakhi/beneficiary_photos/%Y/%m/')),
                ('photo_product', models.ImageField(blank=True, null=True, upload_to='epSakhi/product_photos/%Y/%m/')),
                ('certificate_docs', models.FileField(blank=True, null=True, upload_to='epSakhi/certificates/%Y/%m/')),
                ('beneficiary', models.ForeignKey(db_column='beneficiary_id', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='core.masterbeneficiary')),
                ('recorded_by_user', models.ForeignKey(blank=True, db_column='recorded_by_user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.masteruser')),
            ],
            options={
                'db_table': 'epSakhi_beneficiary_enterprise',
            },
        ),
    ]
